[font]
size = 23
# normal.family = "IosevkaTermNerdFontMono"
# normal.family = "MesloLGS Nerd Font Mono"
normal.family = "UbuntuMonoNerdFont"
# normal.family = "CascadiaCode"
# normal.family = "mono"
# normal.family = "JetBrainsMonoNLNerdFontMono"

[colors.primary]
background = '#212121'
foreground = '#ebdbb2'

[colors.normal]
black   = '#181818'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#448588'
magenta = '#c48084'
cyan    = '#83b273'
white   = '#87786b'

[colors.bright]
black   = '#87786b'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#e69a0e'
blue    = '#83a598'
magenta = '#c58085'
cyan    = '#8ec07c'
white   = '#ebdbb2'
