wallpaper {
    monitor = eDP-1
    # path = ~/archive/wallpapers/view.jpg
    path = /home/white/archive/wallpapers/Gruvbox/irl/fly_agaric_mushroom_fall_foliage_117318_1920x1080.jpg
    # path = /home/white/downloads/Gemini_Generated_Image_ct108yct108yct10.jpg
    fit_mode = cover
}
