monitor = eDP-1, preferred, auto, 1.2

exec-once = waybar
exec-once = hyprsunset --temperature 4500
exec-once = hyprpaper
exec-once = nm-applet --indicator
exec-once = copyq

$mainMod = ALT

env = GTK_THEME=Adwaita-dark

bind = $mainMod_SHIFT, return ,exec, alacritty
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod_SHIFT, SHIFT_R ,exec, pcmanfm
bind = $mainMod_SHIFT, space, togglefloating,
bind = $mainMod, D, exec, wofi --show drun
bind = $mainMod_SHIFT, C, killactive,
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod, F, fullscreen, 0
bind = $mainMod, v, exec, copyq show
bind = ,Print, exec, grim -g "$(slurp)" - | satty --filename=- --floating-hack --action-on-enter save-to-clipboard

bind = ,XF86AudioLowerVolume, exec, ~/scripts/volume down
bind = ,XF86AudioRaiseVolume, exec, ~/scripts/volume up
bind = ,XF86MonBrightnessDown, exec, ~/scripts/brightness down
bind = ,XF86MonBrightnessUp, exec, ~/scripts/brightness up

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod_SHIFT, left, swapwindow, l
bind = $mainMod_SHIFT, right, swapwindow, r
bind = $mainMod_SHIFT, up, swapwindow, u
bind = $mainMod_SHIFT, down, swapwindow, d

bind = $mainMod_SHIFT, h, resizeactive, -60 0
bind = $mainMod_SHIFT, l, resizeactive,  60 0
bind = $mainMod_SHIFT, k, resizeactive,  0 -60
bind = $mainMod_SHIFT, j, resizeactive,  0 60

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, movetoworkspacesilent, 5
bind = $mainMod SHIFT, 6, movetoworkspacesilent, 6
bind = $mainMod SHIFT, 7, movetoworkspacesilent, 7
bind = $mainMod SHIFT, 8, movetoworkspacesilent, 8
bind = $mainMod SHIFT, 9, movetoworkspacesilent, 9
bind = $mainMod SHIFT, 0, movetoworkspacesilent, 10

input {
    kb_layout = us,il
    kb_options = grp:alt_space_toggle

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 to 1.0, 0 means no modification.
    repeat_rate = 50
    repeat_delay = 200
}

general {
    gaps_in = 3
    gaps_out = 12
    border_size = 3
    col.active_border = rgba(770000ff)
    col.inactive_border = rgba(434343aa)
    layout = dwindle
    allow_tearing = false
}

decoration {
    rounding = 0

    blur {
        enabled = true
        size = 5
        passes = 0
    }
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}
