-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprsunset --temperature 4500")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("copyq")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme prefer-dark")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark")
end)

local Mod = "ALT"

hl.env("GTK_THEME", "Adwaita-dark")

hl.bind(Mod .. " + e", function()
    hl.config({ general = { layout = "master" } })
end)

hl.bind(Mod .. " + w", function()
    hl.config({ general = { layout = "monocle" } })
end)

hl.bind(Mod .. " + SHIFT" .. " + return", hl.dsp.exec_cmd("alacritty"))
hl.bind(Mod .. " + M", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(Mod .. " + SHIFT" .. " + SHIFT_R", hl.dsp.exec_cmd("pcmanfm"))
hl.bind(Mod .. " + SHIFT" .. " + space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(Mod .. " + D", hl.dsp.exec_cmd("wofi --show drun"))
hl.bind(Mod .. " + SHIFT" .. " + C", hl.dsp.window.close())
hl.bind(Mod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(Mod .. " + mouse:273", hl.dsp.window.resize())
hl.bind(Mod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(Mod .. " + v", hl.dsp.exec_cmd("copyq show"))
hl.bind("Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | satty --filename=- --early-exit --floating-hack --action-on-enter save-to-clipboard --copy-command wl-copy"))
hl.bind(Mod .. " + Tab", hl.dsp.window.cycle_next())

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("~/scripts/volume down"), { repeating = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("~/scripts/volume up"), { repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("~/scripts/brightness down"), { repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("~/scripts/brightness up"), { repeating = true })

hl.bind(Mod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(Mod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(Mod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(Mod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind(Mod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(Mod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(Mod .. " + SHIFT" .. " + left", hl.dsp.window.swap({ direction = "l" }))
hl.bind(Mod .. " + SHIFT" .. " + right", hl.dsp.window.swap({ direction = "r" }))
hl.bind(Mod .. " + SHIFT" .. " + up", hl.dsp.window.swap({ direction = "u" }))
hl.bind(Mod .. " + SHIFT" .. " + down", hl.dsp.window.swap({ direction = "d" }))

hl.bind(Mod .. " + SHIFT" .. " + h", hl.dsp.window.resize({ x = -60, y = 0, relative = true }))
hl.bind(Mod .. " + SHIFT" .. " + l", hl.dsp.window.resize({ x = 60, y = 0, relative = true }))
hl.bind(Mod .. " + SHIFT" .. " + k", hl.dsp.window.resize({ x = 0, y = -60, relative = true }))
hl.bind(Mod .. " + SHIFT" .. " + j", hl.dsp.window.resize({ x = 0, y = 60, relative = true }))

-- Switch workspaces with Mod + [0-9]
hl.bind(Mod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(Mod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(Mod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(Mod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(Mod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(Mod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(Mod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(Mod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(Mod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(Mod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with Mod + SHIFT + [0-9]
hl.bind(Mod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(Mod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(Mod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(Mod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(Mod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(Mod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(Mod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(Mod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(Mod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(Mod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10, follow = false }))

hl.config({
    input = {
        kb_layout = "us,il",
        kb_options = "grp:alt_space_toggle",
        touchpad = {
            natural_scroll = false,
        },
        sensitivity = 0, -- -1.0 to 1.0, 0 means no modification.
        repeat_rate = 50,
        repeat_delay = 200,
    },
    general = {
        gaps_in = 3,
        gaps_out = 12,
        border_size = 4,
        col = {
            active_border = "rgba(770000ff)",
            inactive_border = "rgba(434343aa)",
        },
        layout = "master",
        allow_tearing = false,
    },
    decoration = {
        rounding = 0,
        blur = {
            enabled = true,
            size = 5,
            passes = 0,
        },
    },
    animations = {
        enabled = true,
    },
})

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 7,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = false,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = false,
    speed = 10,
    bezier = "default",
})
