monitor = eDP-1, preferred, auto, 1.2

exec-once = waybar
exec-once = hyprsunset --temperature 4500
exec-once = hyprpaper
exec-once = nm-applet --indicator
exec-once = copyq

$Mod = ALT

env = GTK_THEME=Adwaita-dark

bind = $Mod_SHIFT, return ,exec, alacritty
bind = $Mod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $Mod_SHIFT, SHIFT_R ,exec, pcmanfm
bind = $Mod_SHIFT, space, togglefloating,
bind = $Mod, D, exec, wofi --show drun
bind = $Mod_SHIFT, C, killactive,
bindm = $Mod, mouse:272, movewindow
bindm = $Mod, mouse:273, resizewindow
bind = $Mod, F, fullscreen, 0
bind = $Mod, v, exec, copyq show
bind = ,Print, exec, grim -g "$(slurp)" - | satty --filename=- --floating-hack --action-on-enter save-to-clipboard

binde = ,XF86AudioLowerVolume, exec, ~/scripts/volume down
binde = ,XF86AudioRaiseVolume, exec, ~/scripts/volume up
bind = ,XF86MonBrightnessDown, exec, ~/scripts/brightness down
bind = ,XF86MonBrightnessUp, exec, ~/scripts/brightness up

bind = $Mod, H, movefocus, l
bind = $Mod, L, movefocus, r
bind = $Mod, K, movefocus, u
bind = $Mod, J, movefocus, d
bind = $Mod, up, movefocus, u
bind = $Mod, down, movefocus, d

bind = $Mod_SHIFT, left, swapwindow, l
bind = $Mod_SHIFT, right, swapwindow, r
bind = $Mod_SHIFT, up, swapwindow, u
bind = $Mod_SHIFT, down, swapwindow, d

bind = $Mod_SHIFT, h, resizeactive, -60 0
bind = $Mod_SHIFT, l, resizeactive,  60 0
bind = $Mod_SHIFT, k, resizeactive,  0 -60
bind = $Mod_SHIFT, j, resizeactive,  0 60

# Switch workspaces with Mod + [0-9]
bind = $Mod, 1, workspace, 1
bind = $Mod, 2, workspace, 2
bind = $Mod, 3, workspace, 3
bind = $Mod, 4, workspace, 4
bind = $Mod, 5, workspace, 5
bind = $Mod, 6, workspace, 6
bind = $Mod, 7, workspace, 7
bind = $Mod, 8, workspace, 8
bind = $Mod, 9, workspace, 9
bind = $Mod, 0, workspace, 10

# Move active window to a workspace with Mod + SHIFT + [0-9]
bind = $Mod SHIFT, 1, movetoworkspacesilent, 1
bind = $Mod SHIFT, 2, movetoworkspacesilent, 2
bind = $Mod SHIFT, 3, movetoworkspacesilent, 3
bind = $Mod SHIFT, 4, movetoworkspacesilent, 4
bind = $Mod SHIFT, 5, movetoworkspacesilent, 5
bind = $Mod SHIFT, 6, movetoworkspacesilent, 6
bind = $Mod SHIFT, 7, movetoworkspacesilent, 7
bind = $Mod SHIFT, 8, movetoworkspacesilent, 8
bind = $Mod SHIFT, 9, movetoworkspacesilent, 9
bind = $Mod SHIFT, 0, movetoworkspacesilent, 10

input {
    kb_layout = us,il
    kb_options = grp:alt_space_toggle

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 to 1.0, 0 means no modification.
    repeat_rate = 50
    repeat_delay = 200
}

general {
    gaps_in = 3
    gaps_out = 12
    border_size = 4
    col.active_border = rgba(770000ff)
    col.inactive_border = rgba(434343aa)
    layout = dwindle
    allow_tearing = false
}

decoration {
    rounding = 0

    blur {
        enabled = true
        size = 5
        passes = 0
    }
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default

    # disabled
    animation = borderangle, 0, 8, default
    animation = border, 0, 10, default
}
