alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias ln='ln -i'
alias vim='nvim'
alias ls='ls --color=always --group-directories-first'
alias grep='grep --color=always'
alias vimrc='cd ~/.config/nvim/'
alias kittyrc='nvim .config/kitty/kitty.conf'
alias tmuxrc='nvim .config/tmux/tmux.conf'
alias tmux='tmux -u'
alias swap='cd ~/.local/state/nvim/swap'
alias image='sxiv'
alias pdf='zathura'
alias ..='cd ..'
alias sl='ls'
alias cal='cal | grep --color -EC6 "\b$(date +%e | sed "s/ //g")"'
alias l='ls -lha --color=always --group-directories-first'
alias ll='ls -lha --color=always --group-directories-first'
alias connectgreen='ssh white@192.168.1.233'
alias du='du -h'
alias startsql='sudo systemctl start mysql'
alias stopsql='sudo systemctl stop mysql'
alias statussql='systemctl status mysql'
alias se='grep -rIn'
alias fk='fg'
alias batcat='batcat --theme=base16'
alias zshrc='cd ~/.config/zsh'
