autoload -U colors && colors

PROMPT='%B%F{magenta}%~%f%b%B%F{green} %b❯ %f'
# PROMPT='%B%F{magenta}%~%f%b%B%F{green} $ %f%b'

# setopt promptsubst
# PS1=$'%F{7}${(r:$COLUMNS::-:)}%f'$PS1

path+=~/archive/.scripts
path+=/usr/local/go/bin
path+=~/.cargo/env

setopt appendhistory
setopt autocd

# autoload -U compinit
# zstyle ':completion:*' menu select
# zmodload zsh/complist
# compinit
# _comp_options+=(globdots)	

source ~/.config/zsh/alias.zsh
source ~/.config/zsh/vi-mode.zsh
source ~/.config/zsh/functions.zsh
source	~/.config/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.config/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/fsh/fast-syntax-highlighting.plugin.zsh
