#!/bin/sh
xset r rate 200 50
xbindkeys
dwmblocks &
xwallpaper --zoom '/home/white/.config/dwm/wall'
setxkbmap -layout us,il -variant , grp:lwin_toggle,terminate:ctrl_alt_bksp
# redshift -l 32.1:34.87 -t 5700:4500 -g 0.8 -m randr -v &
redshift -l 32.1:34.87 -t 5700:5700 -g 0.8 -m randr -v &
setxkbmap -option caps:none
picom &
setxkbmap -layout us,il -variant , grp:alt_space_toggle,terminate:ctrl_alt_bksp
# picom --config ~/.config/picom/picom.conf --experimental-backends &
